### ISSUE TITLE
Node.js build fails on Apple Silicon

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-driver-nodejs#217]
## Problem to Solve

`bazel build //...` fails on an M1 Mac due to our use of deprecated `rules_nodejs`. We should use `rules_js` instead.

(Even getting `rules_js` working on an M1 Mac has been fiddly in the past, but at least it is officially supported. `rules_nodejs` explicitly does not have Apple chip support and will not add it.)

## Current Workaround

Build in CI.

## Proposed Solution

Migrate to `rules_js`, taking inspiration from our other projects using it.

**Comment by flyingsilverfin** [comment]
This is solved as of upgrading all of our build rules and merging drivers into a single repository!
